import { promises as fs } from "fs";
import path from "path";

import { getSupabaseMissingEnv, supabaseRest } from "@/lib/data/supabase";
import {
  DEFAULT_FANTASY_SCORING,
  fromStatic,
  normalizeProjection,
  type FantasyFeed,
  type SupabaseFantasyRow,
} from "@/lib/data/fantasy";

const FANTASY_PATH = path.join(process.cwd(), "public", "data", "fantasy_projections.json");
const CONTEXT_MAX_AGE_MS = 36 * 60 * 60 * 1000;
// The projection statlines make 1,000 rows exceed Next's 2 MB data-cache item
// ceiling. Smaller pages preserve caching while still assembling the full board.
const SUPABASE_PAGE_SIZE = 500;
const SUPABASE_MAX_ROWS = 5000;
const FANTASY_SELECT = [
  "player_id", "player_name", "position", "team", "season", "scope", "week",
  "projected_games", "statline", "statline_low", "statline_high", "points",
  "floor_points", "ceiling_points", "points_per_game", "overall_rank",
  "position_rank", "tier", "adp", "adp_rank", "adp_tier", "adp_source",
  "confidence", "availability", "explanation", "model_version", "updated_at",
].join(",");

async function fetchFantasyRows(scope: "preseason" | "week", season: number, week: number) {
  const rows: SupabaseFantasyRow[] = [];
  for (let offset = 0; offset < SUPABASE_MAX_ROWS; offset += SUPABASE_PAGE_SIZE) {
    const query = `?select=${FANTASY_SELECT}&season=eq.${season}&scope=eq.${scope}&week=eq.${scope === "week" ? week : 0}&order=points.desc&limit=${SUPABASE_PAGE_SIZE}&offset=${offset}`;
    const page = await supabaseRest<SupabaseFantasyRow>(`fantasy_player_projections_latest${query}`);
    if (!page) return rows.length ? rows : null;
    rows.push(...page);
    if (page.length < SUPABASE_PAGE_SIZE) break;
  }
  return rows;
}

async function readStaticFeed(fallbackGaps: string[] = []) {
  // SAFETY: The checked-in fantasy artifact is generated by the fantasy pipeline and matches the Partial<FantasyFeed> input contract.
  const payload = JSON.parse(await fs.readFile(FANTASY_PATH, "utf8")) as Partial<FantasyFeed>;
  return fromStatic(payload, fallbackGaps);
}

function hasFreshContext(feed: FantasyFeed, season: number) {
  if (feed.season !== season || !feed.contextUpdatedAt) return false;
  const updated = Date.parse(feed.contextUpdatedAt);
  return Number.isFinite(updated) && Date.now() - updated <= CONTEXT_MAX_AGE_MS;
}

export async function getFantasyFeed(scope: "preseason" | "week" = "preseason", week = 1): Promise<FantasyFeed> {
  const season = new Date().getUTCFullYear();
  const missing = getSupabaseMissingEnv();
  const rows = await fetchFantasyRows(scope, season, week);
  if (rows?.length) {
    const normalized = rows.map(normalizeProjection);
    let projections = normalized;
    let contextUpdatedAt: string | null = null;
    let sources = ["Supabase fantasy projections"];
    try {
      const staticFeed = await readStaticFeed();
      if (hasFreshContext(staticFeed, season)) {
        const contextById = new Map(staticFeed.projections.map((row) => [row.player_id, row]));
        projections = normalized.map((row) => {
          const context = contextById.get(row.player_id);
          if (!context) return row;
          return {
            ...row,
            team: context.team ?? row.team,
            availability: context.availability,
            roster_status: context.roster_status,
            injury_status: context.injury_status,
            injury_body_part: context.injury_body_part,
            practice_participation: context.practice_participation,
            depth_chart_order: context.depth_chart_order,
            availability_updated_at: context.availability_updated_at,
          };
        });
        contextUpdatedAt = staticFeed.contextUpdatedAt ?? null;
        sources = [...new Set([...sources, ...staticFeed.sources.filter((source) => source.startsWith("Sleeper"))])];
      }
    } catch {
      // Supabase projection rows remain usable when the optional context artifact is absent.
    }
    return {
      generatedAt: rows[0]?.updated_at ?? null,
      contextUpdatedAt,
      season,
      modelVersion: rows[0]?.model_version ?? "fantasy-v1",
      productionStatus: "candidate",
      defaultScoring: DEFAULT_FANTASY_SCORING,
      projections: scope === "preseason" ? projections : [],
      weekly: scope === "week" ? { [String(week)]: projections } : {},
      adp: [],
      metrics: {},
      gaps: [],
      sources,
      dataSource: "supabase",
    };
  }

  try {
    const feed = await readStaticFeed(missing.length ? [`Supabase live feed unavailable: ${missing.join(", ")}.`] : []);
    if (scope === "week") {
      feed.projections = feed.weekly[String(week)] ?? [];
    }
    return feed;
  } catch {
    return {
      generatedAt: null,
      season,
      modelVersion: "fantasy-unavailable",
      productionStatus: "blocked",
      defaultScoring: DEFAULT_FANTASY_SCORING,
      projections: [],
      weekly: {},
      adp: [],
      metrics: {},
      gaps: [...missing.map((item) => `Missing ${item}.`), `No fantasy artifact found at ${FANTASY_PATH}.`],
      sources: [],
      dataSource: "unavailable",
    };
  }
}
